version: "3.9"

services:
  speedtester-garage:
    build: .
    image: speedtester
    restart: always
    container_name: speedtester-garage
    env_file: variables.env
    environment:
      - TEST_SERVICE=garage
      - TEST_TIME=35
    extra_hosts:
      monitoring.nazam.co.uk: 192.168.0.230
    dns:
      - 192.168.0.1
